USE SP_MEDICAL_GROUP_MANHA
GO

SELECT * FROM CLINICA

SELECT * FROM CONSULTA
WHERE CONSULTA.idMedico = 1

SELECT * FROM CONSULTA
WHERE CONSULTA.idPaciente = 3

SELECT COUNT(email) FROM USUARIO

SELECT *, CONVERT(VARCHAR, CONVERT(DATE, dataNascPac, 103), 110) FROM Paciente

EXEC MedicoPorEspecialidade @idEspecialidade = 1

EXEC CalcularIdade 1